/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingdemo;

import java.awt.Color;
import java.sql.*;

/**
 *
 * @author ENVY
 */
public class student extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public student() {
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        initComponents();
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jButton2.setVisible(false);
        jLabel9.setVisible(false);
        
        jComboBox2.removeAllItems();
        jComboBox4.removeAllItems();
        jComboBox1.removeAllItems();
        jComboBox3.removeAllItems();
        
        jComboBox2.addItem("Engineering");
        jComboBox2.setSelectedItem("Engineering");
        jComboBox2.addItem("MCA");
        
        jComboBox1.addItem("Mechanical");
        jComboBox1.setSelectedItem("Mechanical");
        jComboBox1.addItem("Computer");
        //jComboBox1.addItem("Computer");

        jComboBox3.addItem("FE");
        jComboBox3.setSelectedItem("FE");
        jComboBox3.addItem("SE");
        jComboBox3.addItem("TE");
        jComboBox3.addItem("BE");
        
        jComboBox4.addItem("A");
        jComboBox4.setSelectedItem("A");
        jComboBox4.addItem("B");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Department");

        jLabel3.setText("Course");

        jLabel4.setText("Year");

        jButton1.setText("Fill Feedback");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Div");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Teacher's Name:");

        jLabel7.setText("Subject:");

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("No question found!! Please visit again later...");

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("jLabel9");

        jLabel10.setText("Roll no");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(jLabel10)
                                        .addGap(48, 48, 48)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(178, 178, 178)
                                .addComponent(jLabel7))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean boValid = true;
        jLabel9.setVisible(false);
        jLabel1.setForeground(Color.black);
        jLabel10.setForeground(Color.black);
        if (jTextField1.getText().isEmpty() ||
            jComboBox1.getSelectedItem() == "none"  || 
            jComboBox2.getSelectedItem() == "none"  ||
            jComboBox3.getSelectedItem() == "none"  ||
            jComboBox4.getSelectedItem() == "none"  ||
            jTextField2.getText().isEmpty()
           )
        {
            if (jTextField1.getText().isEmpty())
            {
                //display in red colour
                //jLabel9.setForeground(Color.red);
                jLabel9.setText("Name cannot be empty");
                jLabel9.setVisible(true);
                jLabel1.setForeground(Color.red);
            }
            
            if (jTextField2.getText().isEmpty())
            {
                //display in red colour
                //jLabel9.setForeground(Color.red);
                jLabel10.setForeground(Color.red);
            }
            
            boValid = false;
        }
        if (true == boValid)
        {
            jLabel8.setVisible(true);
            jButton2.setText("Exit");
            jButton2.setVisible(true);
            
            //insert student record into student
            insertStudentRecord(
                    jTextField1.getText(),
                    jComboBox1.getSelectedItem().toString(),
                    jComboBox2.getSelectedItem().toString(),
                    jComboBox3.getSelectedItem().toString(),
                    jComboBox4.getSelectedItem().toString(),
                    Integer.parseInt(jTextField2.getText())
                    );
            //fetch questions from database;
            jButton1.setEnabled(false);
            getFeedback();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void insertStudentRecord(
                                String name,
                                String course,
                                String department,
                                String year,
                                String division,
                                int rollNo
                                )
    {
        try
        {
           Statement stmt;
           Connection con;
           jLabel9.setVisible(true);
           jLabel9.setText("");
           if (name.isEmpty()        || 
               course.isEmpty()      ||
               department.isEmpty()  ||
               year.isEmpty()        ||
               division.isEmpty()    ||
               (0 >= rollNo)
              )
           {
               jLabel9.setText("Record could not be added!!");
               return;
           }
           Class.forName("com.mysql.cj.jdbc.Driver");  
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/feedback","root","123456");  
           if (null != con)
           {
               stmt=con.createStatement();  
               if (null != stmt)
               {
                    String ques = "insert into student(name, course, department, year, division, rollNo) values('"+name+
                            "','"+course+
                            "','"+department+
                            "','"+year+
                            "','"+division+
                            "',"+rollNo+
                            ")";
                    stmt.executeUpdate(ques);
                    stmt.close();
                    jLabel9.setForeground(Color.green);
                    jLabel9.setText("Student added successfully");
               }
               else
               {
                   jLabel9.setText("Operation not successful!! Database cannot be connected.");
               }
           }

           if (null != con)
               con.close();
       }
       catch(Exception sql)
       {
           jLabel9.setText("Exception: "+ sql.getMessage());
       }
    }
    
    private void getFeedback()
    {
        
        jButton2.setVisible(true);
        //fetch questions
        try
        {
           Statement stmt;
           Connection con;
           
           Class.forName("com.mysql.cj.jdbc.Driver");  
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/feedback","root","123456");  
           if (null != con)
           {
               stmt=con.createStatement();  
               if (null != stmt)
               {
                    String ques = "select * from feedback_ques";
                    rsQues = stmt.executeQuery(ques);
                    
               }
               else
               {
                   jLabel9.setText("Operation not successful!! Database cannot be connected.");
               }
           }
           
           if(rsQues.next())
           {
                jLabel8.setText(rsQues.getString("question"));
                jButton2.setVisible(true);
                jButton2.setText("Next");
                jButton2.setEnabled(true);
           }
           
           if (null != con)
               con.close();
           
           if (null != stmt)
               stmt.close();
           
           jButton2.setEnabled(false);

       }
       catch(Exception sql)
       {
           jLabel9.setText("Exception: "+ sql.getMessage());
       }
        
    }
    
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
        if (jComboBox2.getSelectedItem() == "MCA")
        {
            jComboBox1.removeAllItems();
            jComboBox3.removeAllItems();
            
            jComboBox1.addItem("Computer");
            jComboBox1.setSelectedItem("Computer");
            jComboBox1.addItem("Management");
            
            jComboBox3.addItem("FY");
            jComboBox3.setSelectedItem("FY");
            jComboBox3.addItem("SY");
            jComboBox3.addItem("TY");
        }
        else if (jComboBox2.getSelectedItem() == "Engineering")
        {
            jComboBox1.removeAllItems();
            jComboBox3.removeAllItems();
            
            jComboBox1.addItem("Mechanical");
            jComboBox1.setSelectedItem("Mechanical");
            jComboBox1.addItem("Computer");
            
            jComboBox3.addItem("FE");
            jComboBox3.setSelectedItem("FE");
            jComboBox3.addItem("SE");
            jComboBox3.addItem("BE");
        }
        
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jLabel8.getText() == "No question found!! Please visit again later...")
        {
            jLabel8.setForeground(Color.green);
            jLabel8.setText("No question found!! Please visit again later...");
            jLabel8.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Demo1 demo = new Demo1();
        demo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    private int noOfQues = 10;
    ResultSet rsQues;
}

